### PR TITLE
Add a hint on how to generate SSH host key

### PR DESCRIPTION
**Pull request by JohnMaguire**
Screen Shot 2022-07-27 at 12 44 55 PM

### CODE REVIEW

**Review by IanVS — APPROVED** [review]
LGTM, although @bgolat, maybe we should change the styles a bit so the inline code blocks don't overlap like this.

**Comment by JohnMaguire** [comment]
> LGTM, although @bgolat, maybe we should change the styles a bit so the inline code blocks don't overlap like this.

The spacing before the inline code block looks a little off to me too. (More space inside the code block than outside.)

**Comment by bgolat** [comment]
> LGTM, although @bgolat, maybe we should change the styles a bit so the inline code blocks don't overlap like this.

That screenshot is using old code styles for some reason.  We don't use those fonts/colors/spacing anymore.

**Comment by IanVS** [comment]
Here's how it looks when built into the website: 

image

We just don't have all the styles fully synced into this project when built outside of the website.

**Pull request merged**
