### PR TITLE
New guide: Extend network access beyond overlay hosts

### PR DESCRIPTION
**Pull request by briankelly**
WIP - not ready to merge

### CODE REVIEW

**Comment by briankelly** [comment]
At long last, this guide is ready for review. All content is in`src/data/docs/en/unsafe_routes.md`. Pinging @rawdigits for accuracy and @IanVS @bgolat for formatting / style review.

Feedback welcome from anyone else who might have thought about using this feature, but didn't get a chance to, yet. :-) 

If you always wanted to access _every_ host on your home network from afar and you have at least one box at home that can run Nebula (like a Raspberry Pi)… your moment has arrived.

**Review by IanVS — COMMENTED** [review]
Any chance we can use a shorter title?  It overflows our mobile nav box:

image

**Review by bgolat — APPROVED** [review]

**Review by IanVS — APPROVED** [review]

**Comment by IanVS** [comment]
@briankelly would you mind doing a find-replace from primes `'` to apostrophes `’`?

**Comment by JohnMaguire** [comment]
> @briankelly would you mind doing a find-replace from primes `'` to apostrophes `’`? Unless maybe I can find a markdown plugin that will do that automatically... That would be better...

Is there a reason for this other than consistency? AFAIK macOS is the only platform that automatically tries to insert apostrophes in place of primes.

**Comment by JohnMaguire** [comment]
https://en.wikipedia.org/wiki/Prime_(symbol)#Computer_encodings

I'm confused - this looks like `'` is actually an apostrophe, and `’` is a prime.

**Comment by IanVS** [comment]
Just me being picky.  An apostrophe is the correct punctuation mark.  https://webdesignledger.com/common-typography-mistakes-apostrophes-versus-quotation-marks/

I think finding a way to convert them automatically is our best bet, or failing that, I'll need to add a linting rule to enforce consistency, since this is open-source and rejecting a PR over nitpicks like this is not cool.

**Comment by jasikpark** [comment]
> @briankelly would you mind doing a find-replace from primes `'` to apostrophes `’`? Unless maybe I can find a markdown plugin that will do that automatically... That would be better...

👀 https://docs.astro.build/guides/markdown-content/index.html#remark-and-rehype-plugins has https://github.com/silvenon/remark-smartypants by default

**Comment by IanVS** [comment]
Thanks @jasikpark.  I should have investigated before piping up.  I'm not sure which plugin is doing it, but astro is converting properly.  Nothing to see here...  :backsawayslowly:

**Review by rawdigits — APPROVED** [review]

**Pull request merged**
