### PR TITLE
Set `onBrokenAnchors` and `onBrokenMarkdownLinks` to `throw`

### PR DESCRIPTION
**Pull request by jasikpark**
- https://docusaurus.io/blog/releases/3.4
	Can enforce that tags are either in the frontmatter or inline w/in content
- https://docusaurus.io/blog/releases/3.3
	Prepares for React 19
- https://docusaurus.io/blog/releases/3.2
	Faster builds
	Faster dev server
	MDX partials TOC (if you add headings via an MDX partial, they can be included in the table of contents now)
- https://docusaurus.io/blog/releases/3.1
	Broken anchors checker

### CODE REVIEW

**Comment by IanVS** [comment]
Any notable changes in these versions?

**Comment by jasikpark** [comment]
added

**Comment by IanVS** [comment]
It's suggested to set `[onBrokenAnchors](https://docusaurus.io/docs/api/docusaurus-config#onBrokenAnchors)` to `"throw"`, can we try that here?

**Comment by jasikpark** [comment]
done!

**Pull request merged**
